### ISSUE TITLE
Cannot fold code

### ISSUE THREAD

**Issue by GammaGames** [ExodiusStudios/vscode-comment-anchors#13] opened 2018-10-01 16:43 UTC
One of the recent updates broke the folding 

![peek 2018-10-01 10-40](https://user-images.githubusercontent.com/7832163/46302563-96138d80-c566-11e8-9e40-c9ca36ac8c4f.gif)

**Comment by macjuul** [comment] 2018-10-01 21:18
Hey Gamma, ive been trying to reproduce this bug with some other people and it seems to happen for about half of them (excluding me). I'll be looking into a fix for this issue, however it would be great if you could share some more setup details (e.g. operating system, extension version, CA settings, etc.) and see if this happens in other files as well. 

Thanks again!

**Comment by Densorius** [comment] 2018-10-01 21:35
Hello there,

With some quick testing, typescript and JavaScript files don't have the bug. But when I change the file type to C#, PHP or java the bug appears.

Also, when I change the file type from for example java to JavaScript the bug persists until I make a change after which the bug disappears.

**Comment by macjuul** [comment] 2018-10-03 21:46
After some more testing I can conclude folding is absolutely buggered in both C# and Java, works flawlessly in JavaScript and TypeScript, but only works in Python without Comment Anchors. Since I'm doing nothing out of the ordinary (simply registering one fold provider) this can only be an issue related to the specific language extensions or VS Code itself.

Since I'm unable to solve this issue, I'll instead implement a setting to disable folding instead.

Hopefully this will still resolve your issues!

**Comment by GammaGames** [comment] 2018-10-03 21:52
That's really weird! I wonder if it's an issue with vsc and if it should be reported. I don't really need anchor folding, so a setting would work well for me. Thank you!

**Comment by macjuul** [comment] 2018-10-04 06:41
Alright, the setting will be available in the next release. I've tested it with python and can confirm it fixes language folding

**Closed by macjuul** 2018-10-04 06:41 UTC

**Comment by GammaGames** [comment] 2018-10-05 17:28
Seems to be working great, thank you :+1:
