### ISSUE TITLE
`SECTION` folding is not working in the editor gutter

### ISSUE THREAD

**Issue by Enteleform** [ExodiusStudios/vscode-comment-anchors#79] opened 2020-05-19 15:00 UTC
I tried using the `SECTION` anchor (*paired with the closing `!SECTION` anchor*), and it is not generating the fold/unfold buttons in the editor gutter.

The sections display as expected in the File Anchors sidebar, with folding & nesting working as expected.

I tested this on the current portable release of VSCode to confirm that it wasn't a conflict with another plugin.

**Comment by macjuul** [comment] 2020-05-19 18:58
Duplicate of #77

TL;DR, the in-editor folding caused more harm than good, and since I personally don't currently have the resources to fix it I opted to remove the feature from the latest release.

**Closed by macjuul** 2020-05-19 18:58 UTC
